# .github/workflows/build.yml
# CI: build every push / PR on the two main OS-families and three relevant JDKs.
# Upload artifacts only once (Linux + JDK 11) to keep noise down.

name: build
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:   [ubuntu-latest, windows-latest]  # ubuntu-22.04 / windows-2025
        java: [1.8, 11, 17]                    # MC minimum, current LTS, latest LTS
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      # Setup JDK + Gradle cache in one go
      - name: Set up JDK ${{ matrix.java }}
        uses: gradle/actions/setup-gradle@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin          # Eclipse Temurin is what Mojang ship

      - name: Make gradlew executable (Unix)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Upload artifacts (only once)
        if: runner.os == 'Linux' && matrix.java == '11'
        uses: actions/upload-artifact@v4
        with:
          name: vectorientation-jars
          path: build/libs/
